### ISSUE TITLE
Last minute changes

### ISSUE THREAD

**Issue by ddesir** [SuperArtisMickens/TTP7-CustomComponents#11]
1. Changed filenames in import statements to correct file names to resolve compile error
2. Seems some of the import statement removals were reverted and new ones added.

**Comment by yauhofung** [comment]
Did you forget to do a `git pull` before you tested the app? The app doesn't compile with your new imports.

**Comment by yauhofung** [comment]
Update: Okay, I see what happened. For some reason, GitHub did not update the filenames when I capitalized them on my local repo.

**Comment by yauhofung** [comment]
Issue closed: Deon fixed the compilation errors by updating the import statements.
