### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by ddesir** [SuperArtisMickens/TTP7-CustomComponents#2]
There are a dozen or so imports that we should remove.

**Comment by yauhofung** [comment]
Which imports in which files specifically?

**Comment by yauhofung** [comment]
Update:

![image](https://user-images.githubusercontent.com/54601881/104506299-331d5780-55b3-11eb-9545-184095838978.png)

**Comment by ddesir** [comment]
I can't seem to find the MiniDrawer.js warning. Otherwise, the other unused imports are resolved.![image](https://user-images.githubusercontent.com/891705/104526233-edbb5300-55cf-11eb-8e84-fc7598f0320f.jpeg)
![image](https://user-images.githubusercontent.com/891705/104526253-f1e77080-55cf-11eb-9d6a-782250d1b8c1.jpeg)

**Comment by yauhofung** [comment]
Issue closed: We will continue to address minor issues in assignment eight.
